name: Disruptivecollaborators
favicon: null
layout_spectrum: 0.09835253120400012
typography_spectrum: 0.2961400889325887
title: Collaborating for future Disruptive Innovations.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.20262969797477126
  lightness: 0.34639793634414673
  saturation: 0.4633101799990982
  rhythmicContrast: 0.4413957947399467
purpose: []
